// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbC6PZLVVo-ISDjVjbeWpLvVhu_eVp_-g',
    appId: '1:633294711891:android:a5aa241a6c830c9d66eaa6',
    messagingSenderId: '633294711891',
    projectId: 'cineverse-4fe46',
    storageBucket: 'cineverse-4fe46.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzJc8-E0uF_cG96OzdaXS7gDto278AYx0',
    appId: '1:633294711891:ios:c2b0e122a375ab8266eaa6',
    messagingSenderId: '633294711891',
    projectId: 'cineverse-4fe46',
    storageBucket: 'cineverse-4fe46.firebasestorage.app',
    androidClientId: '633294711891-pku1rds3tnffpt8no1kmdt0odq0jv4q5.apps.googleusercontent.com',
    iosClientId: '633294711891-tltbb2nvvre2snhm0tsgl3meipajbc4m.apps.googleusercontent.com',
    iosBundleId: 'com.example.cineverse',
  );

}